server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: example
    password: example
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none